sudo: require
services:
  - docker
  
before_install:
  - docker build -t kb/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true kb/docker-react npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name:  "elasticbeanstalk-us-east-2-114878540880"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS-ACCESS-KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"